server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/order/(?<path>.*),/$\{path}
        - id: kitchen-service
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/kitchen/**,/menu-item/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/kitchen/(?<path>.*),/$\{path}
        - id: delivery-service
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/delivery/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery/(?<path>.*),/$\{path}

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000