server:
  port: 8083
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
      org:
        hibernate:
          envers:
            revision_field_name: rev_id
            revision_type_field_name: rev_type
    show-sql: 'true'

  datasource:
    url: jdbc:postgresql://localhost:5432/liga
    password: 'admin'
    username: 'postgres'